/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bryn' at '20/06/16 8:40 PM' with Gradle 2.6
 *
 * @author bryn, @date 20/06/16 8:40 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
